version: "3.8"

services:
  backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backoffice
    ports:
      - 8002:8000
    volumes:
      - .:/app
    networks:
      - blitzvideo-api_default
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=Backoffice
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql-Backoffice
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=Backoffice
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - blitzvideo-api_default
networks:
  blitzvideo-api_default:
    external: true
